blank_issues_enabled: true
contact_links:
    - name: Question
      url: https://github.com/jeffvli/feishin/discussions
      about: Please ask and answer questions here.
    - name: Report a security vulnerability
      url: https://github.com/jeffvli/feishin/security/advisories/new
      about: Privately report a security vulnerability.
