name: Publish Linux Release (Manual)

on: workflow_dispatch

jobs:
    publish:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest]
                arch: ['--linux', '--arm64']

        steps:
            - name: Checkout git repo
              uses: actions/checkout@v1

            - name: Install Node and NPM
              uses: actions/setup-node@v1
              with:
                  node-version: 16
                  cache: npm

            - name: Install dependencies
              run: |
                  npm install --legacy-peer-deps

            - name: Electron Builder Action
              uses: samuelmeuli/action-electron-builder@v1
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  max_attempts: 3
                  build_script_name: 'build'
                  release: true
                  args: ${{ matrix.arch }}
